
---
- name: lesson for varibales
  hosts: all

  vars:
    message1: Privet
    message2: Yoba
    secret: PasswordFromYourAnus

  tasks:
  - name: print some info
    debug:
      var: secret
  - debug:
      msg: "owner of this server is: {{ owner  }}"

  - set_fact: full_message="{{ message1  }} {{ message2  }} from {{ owner  }}"
 
  - debug:
      var: full_message
