
---
- name: Install apache to my server
  hosts: all

  tasks:
  - name: Install apache
    apt: name=apache2 state=latest

  - name: Start apache and Enable
    service: name=apache2 state=started enabled=yes
 
