---
# tasks file for deploy_apache
#
 
 - name: install apache2
   apt: name=apache2 state=latest

 - name: copy my page to server
   copy: src={{ source_file }} dest={{ destin_file }} mode=0555
   notify:
    -  Restart apache

 - name: start server and enable
   service: name=apache2 state=started enabled=yes

